version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"         # ports is a list with a single string mapping
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/beautyCRM"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm","run","dev"]
    networks:
      - crmesteic_default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"         # ports is specified as a list
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","start"] 
    networks:
      - crmesteic_default 
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"       # again, list format
    volumes:
      - /home/leakred18/Desktop/projects/crmesteic/database:/data/db

networks:
  crmesteic_default:
#volumes:
 # mongo_data:
